import type { Metadata } from "next";
import { Albert_Sans, Unbounded } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Layout from "@/components/layout";

const unbounded = Unbounded({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-unbounded",
});
const albertSans = Albert_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-albert-sans",
});
const theSignature = localFont({
  src: [
    {
      path: "../public/font/the-signature/Thesignature.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/the-signature/Thesignature.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-the-signature",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.variable} ${albertSans.variable} ${theSignature.variable}`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
